services:
 backend-intelliquiz:
  container_name: backend-intelliquiz
  build:
   context: .
   target: development
  ports:
   - 8080:8080
  env_file:
    - ./.env
  depends_on:
   - postgres
  volumes:
   - ./src/:/intelliquiz/src
 postgres:
  container_name: postgres
  image: postgres:17
  environment:
   POSTGRES_USER: pgadmin
   POSTGRES_PASSWORD: pgadmin
   POSTGRES_DB: intelliquiz
  ports:
   - 5432:5432
  volumes:
   - postgres-data:/var/lib/postgresql/data
volumes:
 postgres-data: